version: "3.8"

services:
  ubuntu:
    build:
      context: ./
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - TZ=${TZ}
        - LANG=${LANG}
        - USER_NAME=${USER_NAME}
    tty: true
